version: '2'
services:
  LoadBalancer:
    start_on_create: true
    lb_config:
      certs: []
      default_cert: certificat-letsencrypt
      port_rules:
      - hostname: miligo.zyra.fr
        path: ''
        priority: 5
        protocol: https
        service: Miligo/payara
        source_port: 443
        target_port: 8080
      stickiness_policy:
        cookie: sticky
        domain: miligo.zyra.fr
        indirect: false
        mode: insert
        nocache: false
        postonly: false
    health_check:
      healthy_threshold: 2
      response_timeout: 2000
      port: 42
      unhealthy_threshold: 3
      initializing_timeout: 60000
      interval: 2000
      reinitializing_timeout: 60000
